export const products = [
  {
    id: 1,
    name: "Viaje a Nueva York",
    srcImage: require("./../src/assets/products/new-york.jpg"),
    description: "Descripción del artículo, esto es una descripción de prueba para un viaje",
    price: 11,
  },
  {
    id: 2,
    name: "Viaje a Londres",
    srcImage: require("./../src/assets/products/london.jpg"),
    description: "Descripción del artículo, esto es una descripción de prueba para un viaje",
    price: 22,
  },
  {
    id: 3,
    name: "Viaje a París",
    srcImage: require("./../src/assets/products/paris.jpg"),
    description: "Descripción del artículo, esto es una descripción de prueba para un viaje",
    price: 33,
  },
  {
    id: 4,
    name: "Viaje a Roma",
    srcImage: require("./../src/assets/products/rome.jpg"),
    description: "Descripción del artículo, esto es una descripción de prueba para un viaje",
    price: 54,
  },
  {
    id: 5,
    name: "Viaje a Madrid",
    srcImage: require("./../src/assets/products/madrid.jpg"),
    description: "Descripción del artículo, esto es una descripción de prueba para un viaje",
    price: 65,
  },
  {
    id: 6,
    name: "Viaje a Barcelona",
    srcImage: require("./../src/assets/products/barcelona.jpg"),
    description: "Descripción del artículo, esto es una descripción de prueba para un viaje",
    price: 76,
  },
  {
    id: 7,
    name: "Viaje a Berlín",
    srcImage: require("./../src/assets/products/berlin.jpg"),
    description: "Descripción del artículo, esto es una descripción de prueba para un viaje",
    price: 87,
  },
  {
    id: 8,
    name: "Viaje a Praga",
    srcImage: require("./../src/assets/products/praga.jpg"),
    description: "Descripción del artículo, esto es una descripción de prueba para un viaje",
    price: 98,
  },
  {
    id: 9,
    name: "Viaje a Amsterdam",
    srcImage: require("./../src/assets/products/amsterdam.jpg"),
    description: "Descripción del artículo, esto es una descripción de prueba para un viaje",
    price: 109,
  },
  {
    id: 10,
    name: "Viaje a Budapest",
    srcImage: require("./../src/assets/products/budapest.jpg"),
    description: "Descripción del artículo, esto es una descripción de prueba para un viaje",
    price: 55,
  },
  {
    id: 11,
    name: "Viaje a Viena",
    srcImage: require("./../src/assets/products/viena.jpg"),
    description: "Descripción del artículo, esto es una descripción de prueba para un viaje",
    price: 12,
  },
  {
    id: 12,
    name: "Viaje a Lisboa",
    srcImage: require("./../src/assets/products/lisboa.jpg"),
    description: "Descripción del artículo, esto es una descripción de prueba para un viaje",
    price: 66,
  },
];
