const MODIFY_PUJA = "MODIFY_PUJA";
const ADD_USERS = "ADD_USERS";
const CLOSE_CLIENT = "CLOSE_CLIENT";
const SEND_PRIVATE_MESSAGE = "SEND_PRIVATE_MESSAGE";

module.exports = {
  MODIFY_PUJA,
  ADD_USERS,
  CLOSE_CLIENT,
  SEND_PRIVATE_MESSAGE,
};
